#server:
#  port: 8010
food:
  meat: 烤肉
  rice: 拌饭
  sauce:
    - 咖喱
    - 牛肉
#spring:
#   profiles:
#     active: dev
#---
#server:
#  port: 8096
#spring:
#  profiles: dev
#
#---
#spring:
#  profiles: prod
#server:
jasypt:
  encryptor:
    password: 123456!@#

info:
  username: ENC(xCVQt5QTjiQ/OXRxmWTu9Q==)
  password: ENC(GQ2KLM1wFsUWfFA5au9JkQ==)
#  port: 8097